In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('student_performance.csv')

In [4]:
print("Dataset loaded successfully")

Dataset loaded successfully

In [5]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [6]:
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [8]:
print("Shape of dataset:",df.shape)

Shape of dataset: (30, 13)

In [9]:
print("Number of rows:",df.shape)

Number of rows: (30, 13)

In [10]:
print("Number of rows:",df.shape[0])

Number of rows: 30

In [11]:
print("Number of rows:",df.shape[1])

Number of rows: 13

In [12]:
df.dtypes

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [13]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [14]:
print("Columns in the dataset:")
print(df.columns.tolist())

Columns in the dataset:
['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [15]:
df.columns.tolist()

['student_id',
 'name',
 'age',
 'gender',
 'department',
 'semester',
 'math_score',
 'science_score',
 'english_score',
 'programming_score',
 'attendance_percentage',
 'city',
 'admission_year']

In [16]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [17]:
print("Data types:")
print(df.dtypes)

Data types:
student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [18]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [20]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [21]:
print("\nTotal missing values:",df.isnull().sum().sum())

Total missing values: 0

In [22]:
print("Student Names:")
print(df['name'])

Student Names:
0       Aarav Sharma
1        Priya Patel
2        Rohit Verma
3        Sneha Reddy
4         Arjun Nair
5        Meera Joshi
6        Kiran Kumar
7        Divya Singh
8       Rahul Mishra
9         Ananya Das
10       Vikram Iyer
11       Pooja Gupta
12        Suresh Rao
13     Kavya Nambiar
14       Ajay Tiwari
15      Ritu Agarwal
16      Manoj Pandey
17    Swati Kulkarni
18    Deepak Chauhan
19      Nisha Kapoor
20     Harish Pillai
21       Tanvi Mehta
22      Sanjay Dubey
23     Preeti Saxena
24         Amit Bose
25        Rekha Nair
26     Gaurav Shukla
27     Sunita Pillai
28        Nitin Jain
29    Akanksha Yadav
Name: name, dtype: object

In [23]:
print("Departments in this dataset:")
print(df['department'].unique())

Departments in this dataset:
['Computer Science' 'Electronics' 'Mechanical' 'Civil']

In [24]:
print("\nHow many students per department:")
print(df['department'].value_counts())

How many students per department:
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [25]:
cs_students=df[df['department']=='computer science']

In [26]:
print(f"Number of computer science students:{len(cs_students)}")

Number of computer science students:0

In [27]:
print("\ncomputer science students:")

computer science students:

In [32]:
high_attendance=df[df['attendance_percentage']>90]

In [37]:
print("Students with attendance above 90%:", (len(high_attendance)))
print(high_attendance[['name','department','attendance_percentage']])

Students with attendance above 90%: 10
              name        department  attendance_percentage
0     Aarav Sharma  Computer Science                     92
3      Sneha Reddy        Mechanical                     95
7      Divya Singh  Computer Science                     96
9       Ananya Das  Computer Science                     98
13   Kavya Nambiar        Mechanical                     91
15    Ritu Agarwal       Electronics                     93
17  Swati Kulkarni  Computer Science                     94
21     Tanvi Mehta  Computer Science                     97
24       Amit Bose  Computer Science                     91
29  Akanksha Yadav  Computer Science                     95

In [39]:
df['total_score']=df['math_score']+df['science_score']+df['english_score']+df['programming_score']

In [42]:
top_student=df.loc[df['total_score'].idxmax()]

In [48]:
print("Top Student:")
print(f"Name:{top_student['name']}")
print(f"Department:{top_student['department']}")
print(f"Total Score:{top_student['total_score']}")
print(f"Attendance:{top_student['attendance_percentage']}")

Top Student:
Name:Ananya Das
Department:Computer Science
Total Score:274
Attendance:98

In [49]:
dept_avg=df.groupby('department')['total_score'].mean().round(2)

In [50]:
print("Average Total Score by Department:")
print(dept_avg)

Average Total Score by Department:
department
Civil               195.20
Computer Science    250.92
Electronics         216.00
Mechanical          218.00
Name: total_score, dtype: float64

In [51]:
df_sorted=df.sort_values(by='total_score',ascending=False)

In [53]:
print("Top 10 Students by Total Score:")
print(df_sorted[['name','department','total_score','attendance_percentage']].head(10))

Top 10 Students by Total Score:
              name        department  total_score  attendance_percentage
9       Ananya Das  Computer Science          274                     98
21     Tanvi Mehta  Computer Science          271                     97
29  Akanksha Yadav  Computer Science          271                     95
7      Divya Singh  Computer Science          263                     96
17  Swati Kulkarni  Computer Science          262                     94
4       Arjun Nair  Computer Science          261                     90
15    Ritu Agarwal       Electronics          256                     93
24       Amit Bose  Computer Science          247                     91
1      Priya Patel  Computer Science          246                     87
12      Suresh Rao  Computer Science          246                     88

In [54]:
print("=" * 50)
print("      STUDENT PERFORMANCE EXPLORER")
print("=" * 50)

==================================================
      STUDENT PERFORMANCE EXPLORER
==================================================

In [56]:
print("\nDATASET OVERVIEW")
print("-" * 30)
print("Total Number of Students:", len(df))
print("Total Number of Columns:", len(df.columns))
print("Number of Unique Departments:", df['department'].nunique())

DATASET OVERVIEW
------------------------------
Total Number of Students: 30
Total Number of Columns: 14
Number of Unique Departments: 4

In [58]:
print("\nDEPARTMENT-WISE ANALYSIS")
print("-" * 30)
print(df['department'].value_counts())

DEPARTMENT-WISE ANALYSIS
------------------------------
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [59]:
print("\nSCORE ANALYSIS")
print("-" * 30)
print("Highest Math Score:", df['math_score'].max())
print("Lowest Math Score:", df['math_score'].min())
print("Average Math Score:", df['math_score'].mean())
print("Average Programming Score:", df['programming_score'].mean())
print("Average Attendance Percentage:", df['attendance_percentage'].mean())

SCORE ANALYSIS
------------------------------
Highest Math Score: 95
Lowest Math Score: 56
Average Math Score: 76.06666666666666
Average Programming Score: 67.6
Average Attendance Percentage: 84.5

In [60]:
print("\nGENDER-WISE ANALYSIS")
print("-" * 30)
gender_avg = df.groupby('gender')['total_score'].mean()
print(gender_avg)

GENDER-WISE ANALYSIS
------------------------------
gender
Female    240.466667
Male      215.666667
Name: total_score, dtype: float64

In [62]:
print("\nTOP 5 STUDENTS")
print("-" * 30)

top_students = df.sort_values(by='total_score', ascending=False).head(5)

for index, student in top_students.iterrows():
    print(f"Name: {student['name']}")
    print(f"Department: {student['department']}")
    print(f"Total Score: {student['total_score']}")
    print("-" * 20)

TOP 5 STUDENTS
------------------------------
Name: Ananya Das
Department: Computer Science
Total Score: 274
--------------------
Name: Tanvi Mehta
Department: Computer Science
Total Score: 271
--------------------
Name: Akanksha Yadav
Department: Computer Science
Total Score: 271
--------------------
Name: Divya Singh
Department: Computer Science
Total Score: 263
--------------------
Name: Swati Kulkarni
Department: Computer Science
Total Score: 262
--------------------

In [64]:
print("\nATTENDANCE ANALYSIS")
print("-" * 30)

low_attendance = df[df['attendance_percentage'] < 75]

if low_attendance.empty:
    print("All students have attendance above 75%")
else:
    for index, student in low_attendance.iterrows():
        print(f"Name: {student['name']}")
        print(f"Department: {student['department']}")
        print(f"Attendance Percentage: {student['attendance_percentage']}%")
        print("-" * 20)

ATTENDANCE ANALYSIS
------------------------------
Name: Meera Joshi
Department: Electronics
Attendance Percentage: 72%
--------------------
Name: Rahul Mishra
Department: Mechanical
Attendance Percentage: 68%
--------------------
Name: Manoj Pandey
Department: Civil
Attendance Percentage: 65%
--------------------
Name: Harish Pillai
Department: Electronics
Attendance Percentage: 74%
--------------------
Name: Sanjay Dubey
Department: Civil
Attendance Percentage: 70%
--------------------
Name: Sunita Pillai
Department: Civil
Attendance Percentage: 73%
--------------------